### ISSUE TITLE
Replace Blob with blob

### ISSUE THREAD

**Issue by mamacdon** [avoidwork/haro#57]
Haro depends on `Blob@~0.10.0`, which seems like a bug. That dependency is literally just a "TODO", it has [no code and no license](https://github.com/coolaj86/node-file-api/tree/master/Blob).

I think the intent was to use lowercase `blob` instead, which is a [real library](https://www.npmjs.com/package/blob) that provides the blob constructor.

**Comment by avoidwork** [comment]
hah. most likely.

**Comment by avoidwork** [comment]
i'll check it out tonight or on the weekend; unsure if it's even needed any more.

**Comment by avoidwork** [comment]
So it turns out both are useless for the intended purpose. `blob` exports `undefined` because it just wraps `window.Blob` which doesn't exist (front-end code in npm O_o) so it's actually surfacing a flaw in the code that the other `Blob` module was hiding by having no exports, and having `require()` fill in the missing export with `{}`.

I'll remove the dependency and fix the mistake in code.

**Comment by avoidwork** [comment]
@mamacdon thanks for bringing this to my attention 👍
